version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: server/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  server:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: server
    ports:
      - '4000:4000'
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/prisma
  client:
    container_name: client
    ports:
      - '3000:3000'
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

volumes: #define our mysql volume used above
  mysql: